# default configuration file

app_name: 'Default app'
logging_level: DEBUG
database_uri : postgresql://kolamor:test@localhost:5432/test_api_es
start_connection_rmq: True
connection_rmq_uri : amqp://user:bitnami@127.0.0.1/
json_scheme_path: {
  ElasticV1: "app/handlers/validation_json_templates/s—Åhema_v1.json"
}
http_client_limit_TCPConnector: 0
http_client_limit_per_host_TCPConnector: 0